---
- name: Perform Pre-Installation Tasks
  include_tasks: prerequisites.yaml

- name: Tear down existing services
  docker_compose:
    project_src: "{{ project_remote_dir }}/flaskAPIwDocker"
    state: absent

- name: Create and start services
  docker_compose:
    project_src: flaskAPIwDocker
  register: output

- debug:
    var: output

- name: Run `docker-compose up` again
  docker_compose:
    project_src: "{{ project_remote_dir }}/flaskAPIwDocker"
    build: no
  register: output

- debug:
    var: output

- assert:
    that: "not output.changed "

- name: Stop all services
  docker_compose:
    project_src: "{{ project_remote_dir }}/flaskAPIwDocker"
    build: no
    stopped: yes
  register: output

- debug:
    var: output

- assert:
    that:
      - "not web.{{ api_image_name }}.state.running"

- name: Restart all services
  docker_compose:
    project_src: "{{ project_remote_dir }}/flaskAPIwDocker"
    build: no
    restarted: yes
  register: output

- debug:
    var: output

- assert:
    that:
      - "web.{{ api_image_name }}.state.running"
